import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';

// Precache assets generated by webpack
precacheAndRoute(self.__WB_MANIFEST);

// Cache API responses
/*registerRoute(
    ({ request }) => request.destination === 'document' || request.destination === 'script' || request.destination === 'style',
    new StaleWhileRevalidate()
);

// Optionally, cache other assets like images
registerRoute(
    ({ request }) => request.destination === 'image',
    new StaleWhileRevalidate()
);*/
self.addEventListener('install', (event) => {
    console.log("install event", event)
    self.skipWaiting();
});
self.addEventListener('activate', (event) => {
    console.log("activate event", event)
    self.clients.claim();
});

registerRoute(
    // Match any request that starts with the base URL for todos API
    ({ url }) => url.href.startsWith('https://65c7a2b5e7c384aada6ec54f.mockapi.io/todos'),
    // Use StaleWhileRevalidate strategy to serve from cache while updating in the background
    new CacheFirst({
        cacheName: 'todos-CacheFirst'
    })
);
